project:
  type: website

website:
  title: "Practical Recipes for Data Science"
  favicon: images/siamese-cat.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JunDamins
format:
  html:
    theme: lux
    css: styles.css


