project:
  type: book

book:
  title: "languages4ds"
  author: "Jane Doe"
  date: "9/16/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - setup.qmd
    - syntax.qmd
    - dataframe.qmd
    - visualization.qmd
    - statistics.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{kotex}
    mainfont: NanumMyeongjo