---
title: ADP 준비 (1)
date: 2024-02-02
draft: false
categories:
  - ADP
  - test
  - data
  - tutorial
---

## 데이터 분석 관련한 자격증

[ADP](https://www.dataq.or.kr/www/sub/a_05.do)는 `Advacned Data anlytics Professional`의 약자어로 [한국데이터산업진흥원](https://www.kdata.or.kr/)에서 운영하는 데이터분석 전문가 자격증입니다.

### 국가자격증은 아닌 국가공인 자격증

ADP는 공공기관에서 운영하지만 부류는 기술사나 기사와 같은 국가자격증이 아닌, 민간자격증으로 분류됩니다. 2016년부터는 국가공인을 받은 민간 자격증으로 변경되었습니다.

### 합격률이 3%가 되지 않은 난이도

과거 기록을 보면 2019년을 기점으로 접수자와 응시자가 폭발적으로 증가하였습니다. 응시자가 늘어나면서 합격률도 소폭 하락한 것을 볼 수 있는데 시험에 대한 인식이 생겨나면서 이전 보다 많은 사람들이 도전하면서 합격률이 다소 떨어지는 것이 아닐까 추측해 봅니다.

|          |              |          |          |          |          |        |
|:--------:|:------------:|:--------:|:--------:|:--------:|:--------:|:------:|
| 검정연도 |   자격등급   | 검정횟수 | 접수자수 | 응시자수 | 취득자수 | 합격률 |
|   2022   | 전문가(공인) |    4     |  3,525   |  2,737   |    69    |  2.52  |
|   2021   | 전문가(공인) |    4     |  3,205   |  2,436   |    66    |  2.71  |
|   2020   | 전문가(공인) |    4     |  2,074   |  1,664   |    32    |  1.92  |
|   2019   | 전문가(공인) |    4     |  1,516   |  1,267   |    35    |  2.76  |
|   2018   | 전문가(공인) |    4     |   585    |   501    |    18    |  3.59  |
|   2017   | 전문가(공인) |    4     |   425    |   368    |    14    |  3.8   |
|   2016   | 전문가(공인) |    4     |   300    |   259    |    6     |  2.32  |
|   2015   |    전문가    |    4     |   196    |   137    |    7     |  5.11  |
|   2014   |    전문가    |    6     |   415    |   248    |    8     |  3.23  |

### 데이터 역량을 보여 주는 도구로 주목

ADP는 빅데이터기사와 같은 국가기술자격증은 아님에도 점점 더 많은 사람들이 응시하고 있습니다. 여러가지 이유가 있겠지만, 아주 낮은 홥격률이라는 지점과 데이터 관련한 지식을 보유함을 보여 줄 수 있는 좋은 방법 중 하나로 인식되고 있다고 보고 있습니다.

특히 취업을 준비하거나 직종을 바꾸고 싶은 사람이 자신의 데이터 역량을 보여주는 방법 중 하나로 고려하는 것으로 추측해 봅니다.

현업에게는 그리 의미가 크지는 않을 수 있으나 대기업이나 공공기관에서는 국가공인 자격증으로 의의가 있는 것으로 보입니다. 특히 기업 내에서 자신의 역할을 바꾸고자 할 때 유용하게 사용될 수 있다고 생각합니다.

## 응시 방법

시험은 필기와 실기로 구성되어 있으며, 각각 연 2회 진행됩니다. 필기를 합격한 사람만 실기에 지원할 수 있는 방식으로 2024년 부터는 필기 결과 발표날에 실기시험 모집이 시작됩니다. 시험일시 약 2개월 전에 등록을 할 수 있고 결과 발표까지 한달여 시간이 소요되어 최소 5개월 정도 소요된다고 볼 수 있습니다.

### 필기시험의 범위

시험범위는 유료로 판매되고 있는 [가이드북](https://product.kyobobook.co.kr/detail/S000001399866)을 통해 확인할 수 있습니다. 홈페이지에서는 아래와 같은 목차를 안내하고 있습니다.

1.  데이터 이해
    1.  데이터의 이해
        1.  데이터와 정보
        2.  데이터베이스의 정의와 특징
        3.  데이터베이스 활용
    2.  데이터의 가치와 미래
        1.  빅데이터의 이해
        2.  빅데이터의 가치와 영향
        3.  비즈니스 모델
        4.  위기 요인과 통제 방안
        5.  미래의 빅데이터
    3.  가치 창조를 위한 데이터 사이언스와 전략 인사이트
        1.  빅데이터분석과 전략 인사이트
        2.  전략 인사이트 도출을 위한 필요 역량
        3.  빅데이터 그리고 데이터 사이언스의 미래
2.  데이터 처리 기술 이해
    1.  데이터 처리 프로세스
        1.  ETL(Extraction, Transformation and Load)
        2.  CDC(Change Data Capture)
        3.  EAI(Enterprise Application Integration)
        4.  데이터 연계 및 통합 기법 요약
        5.  대용량 비정형 데이터 처리
    2.  데이터 처리 기술
        1.  분산 데이터 저장 기술
        2.  분산 컴퓨팅 기술
        3.  클라우드 인프라 기술
3.  데이터분석 기획
    1.  데이터분석 기획의 이해
        1.  분석 기획 방향성 도출
        2.  분석 방법론
        3.  분석 과제 발굴
        4.  분석 프로젝트 관리 방안
    2.  분석 마스터 플랜
        1.  마스터 플랜 수립
        2.  분석 거버넌스 체계 수립
4.  데이터분석
    1.  R기초와 데이터 마트
        1.  R기초
        2.  데이터 마트
        3.  결측값 처리와 이상값 검색
    2.  통계분석
        1.  통계학 개론
        2.  기초 통계분석
        3.  다변량 분석
        4.  시계열 예측
    3.  정형 데이터 마이닝
        1.  데이터 마이닝 개요
        2.  분류분석(Classification)
        3.  군집분석(Clustering)
        4.  연관분석(Association Analysis)
    4.  비정형 데이터 마이닝
        1.  텍스트 마이닝
        2.  사회연결망 분석
5.  데이터 시각화
    1.  시각화 인사이트 프로세스
        1.  시각화 인사이트 프로세스의 의미
        2.  탐색(1단계)
        3.  분석(2단계)
        4.  활용(3단계)
    2.  시각화 디자인
        1.  시각화의 정의
        2.  시각화 프로세스
        3.  시각화 방법
        4.  빅데이터와 시각화 디자인
    3.  시각화 구현
        1.  시각화 구현 개요
        2.  분석 도구를 이용한 시각화 구현
        3.  라이브러리 기반의 시각화 구현: D3.js

### 실기시험의 범위

실기 시험은 범위를 지정하고 있지 않으나 크게 머신러닝과 통계라는 구분으로 문제가 구성되어 있습니다. 시험에서 다루는 범주가 모호하기 때문에 준비하는 것이 상당히 막막한 시험입니다. 또한 시험 합격률도 낮아 시험 보는 것이 돈이 아깝게 느껴질 때가 있습니다.

실기시험을 준비해 나가면서 정리한 내용을 게시 하겠습니다.