---
title: ADP 29회 실기 문제 풀기
date: 2023-10-21
draft: true
cagetory:
  - ADP
  - test
code-fold: true
execute:
  eval: false
  
---

## 1.

### 1. 계약자고유번호를 기준으로 거주연도 별 여러개의 데이터가 쌓여 있다. 각 계약자 고유번호에 대해 가장 최신의 거주연도 행만 남겨라.

대구도시공사_빅데이터_영구임대아파트 입주자 퇴거여부 데이터 입니다. 고유번호를 가진 계약자와 특정 아파트에 대해 매년 퇴거 여부를 기록했습니다.

```{python}
import pandas as pd
import ydata_profiling

df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/29/p1.csv',encoding= 'cp949')
df.head()
```

#### 답안

이 문제는 Split-apply-combine 전략이 적절해 보입니다. pandas에서는 groupby를 통해 이 문제를 해결할 수 있습니다.

순번대로 정렬 되어 있다고 가정할 수 있다면 가장 마지막 행을 추출하면 됩니다.

```{python}
# df는 당신의 데이터 프레임입니다.
# '계약자고유번호'를 기준으로 그룹화하고, 각 그룹에서 '거주연도'가 가장 큰 행의 인덱스를 찾습니다.
idx = df.groupby('계약자고유번호')['거주연도'].idxmax()

# 해당 인덱스로 구성된 데이터 프레임을 얻습니다.
df_latest = df.loc[idx]
```

### EDA 및 결측치 처리

일단 EDA를 해봅니다. 결측치 처리를 위해서 많이 사용하는 패키지는 `missingno`입니다. `matplotlib`을 기반으로 하고 있는 패지키로, 한글 폰트를 기본 지원하지 않는 `matplotlib`이기 때문에 한글 폰트를 설정합니다. (폰트 family는 잘 찾아서 집어넣어야 합니다)

```{python}
import missingno as msno
import matplotlib.pyplot as plt

plt.rc('font', family='NanumBarunGothic')

msno.matrix(data)
```

#### EDA하기

1.  데이터의 형태 확인: `df.head()`, `df.tail()` 등의 함수를 사용하여 데이터의 기본적인 형태를 파악합니다.
2.  요약 통계 확인: `df.describe()` 함수를 사용하여 숫자형 변수들에 대한 요약 통계량을 확인합니다.
3.  결측치 확인: `df.isnull().sum()` 등을 사용하여 각 열에서 결측치가 얼마나 있는지 확인합니다.
4.  데이터 타입 확인: `df.dtypes`을 사용하여 각 열의 데이터 타입을 확인합니다.
5.  상관 관계 분석: 숫자형 변수들 간의 상관 관계를 살펴보는 것이 유용할 수 있습니다. 이는 `df.corr()`와 같은 함수로 수행할 수 있습니다.
6.  시각화: `matplotlib`, `seaborn` 등의 라이브러리를 활용해 히스토그램, 박스 플롯, 산점도 등을 그려서 변수들의 분포와 관계를 파악하는 것이 도움이 됩니다.

#### profiling 활용하기

그래프를 보면 퇴거연도에 결측치가 많은 것을 볼 수 있습니다. 이는 아직 거주하기 때문으로 추정해 볼 수 있습니다.

빠르게 EDA를 해보기 위해서 우선 pandas profiling을 사용해봅니다.

```{python}
report = data.profile_report()
report
```

살펴보면 퇴거연도 결측치가 큰 것을 볼 수 있습니다. 이외에 missing값은 아파트 평점입니다. 이는 동일한 아파트의 동일한 연도를 찾아 처리할 수 있습니다.

### 이상치 처리

특이한 값을 찾아보았을 때 나이에서 120세가 있습니다.

월세와 보증금 값 분포에 이상치가 있는 것으로 보입니다.

### 재계약 횟수의 중앙값을 기준으로 중앙값보다 크거나 같으면 "높음", 작으면 "낮음"으로 재계약 횟수 이분 변수를 구성하시오.

```{python}

data["재계약횟수이분"] = data["재계약횟수"].apply(lambda value: "높음" if value >= data["재계약횟수"].median() else "낮음")
data
```

### 차원축소 필요성을 논하고, 필요에 따라 차원을 축소하고 불필요하다면 그 근거를 논하시오.

상관관계가 높은 변수들이 있어 차원 축소를 통해 다중공산성을 해소할 수 있을 것으로 판단됩니다.

다만, 차원 축소 필요 여부는 분석 목적에 달려 있으며 단순히 예측을 목적으로 할 때에는 차원 축소는 불필요 할 수 있습니다.

이 문제에서는 회귀 분석을 이후 진행하는 것을 보았을 때 차원 축소가 필요하다고 판단되며 재계약횟수 이분변수에 대한 분류 분석을 진행 할 때는 선택적인 사항을 판단 됩니다.

cross validation을 달성할 수 있을지 생각해 봅니다.

### 재계약 횟수 이분변수를 기준으로 세그먼트를 구분하고, 각 세그먼트의 특징을 분석하시오.

어떤 부분들에 대해서 논의하면 좋을지 생각해 보게 됩니다.

### 재계약 횟수 변수를 종속변수로 하는 회귀 분석을 두가지 이상의 방법론을 통해 수행하고 최종 모델을 결정하시오. 재계약 횟수 이분변수를 종속변수로 하는 분류 분석을 두가지 이상의 방법론을 통해 수행하고 최종 모델을 결정하시오.

이 파트는 시간을 얼마나 빠르게 처리하느냐에 달려 있을 것으로 보입니다.

### 최종 채택한 모델에서 각각 유의하게 작용하는 변수를 확인하고 설명하시오

방법론에 따라서 변수를 찾는 방법이 다를 것으로 보입니다.

### 해당 데이터 분석 결과로 얻을 수 있는 점을 제시하시오

이부분은 시간이 많이 필요할 것으로 보입니다.

### 4. 각회차별로 1번 타자의 출루(1,2,3루타와 사사구(볼넷, 몸에 맞는 공))가 있을 경우에 대해 득점이 발생 했는지 확인하고자 한다. 이를 위한 전처리를 수행하라.